# Worktree設定テンプレート
# プロジェクト開始時にboss1が具体的な機能名で更新する

worktrees:
  president:
    branch: main
    role: president
    purpose: "最終統合・品質管理・リリース"
    
  boss1:
    branch: integration/phase-1
    role: boss1  
    purpose: "worker成果統合・中間調整"
    
  worker1:
    branch: feature/[scope]/[function-name]
    role: worker1
    purpose: "[担当機能の説明]"
    
  worker2:
    branch: feature/[scope]/[function-name]
    role: worker2
    purpose: "[担当機能の説明]"
    
  worker3:
    branch: feature/[scope]/[function-name]
    role: worker3
    purpose: "[担当機能の説明]"

# ブランチ命名規則
# {type}/{scope}/{description}
# type: feature, fix, refactor, docs, test, infra
# scope: 機能領域（frontend, backend, api, ui, db, etc）
# description: 具体的な機能名（kebab-case）

sync_rules:
  - "変更前に他workerに通知"
  - "共通ファイル編集時は調整必須"  
  - "定期的にmainからrebase"
  - "boss1経由でpresidentに統合"